FROM node:lts-bookworm-slim as react-builder
WORKDIR /app
COPY webview/package*.json ./
RUN npm ci
COPY webview/ ./
RUN npm run build

FROM nginx:stable-bookworm

COPY --from=react-builder /app/dist /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d/default.conf.template.prod /etc/nginx/templates/default.conf.template

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]